### PR TITLE
Fix: #68 Error on Completion frame resize

### PR DESCRIPTION
**Pull request by larebsyed**
** Proposed quick fix:

Wrapped code with a conditional check to avoid nil value of child frame

### CODE REVIEW

**Comment by larebsyed** [comment]
@sebastiencs Can you plesae look into this?

**Comment by larebsyed** [comment]
@sebastiencs This issue still is happening on the latest package, what are your thoughts on merging this PR?

**Comment by larebsyed** [comment]
Bump @sebastiencs

**Comment by sebastiencs** [comment]
Thanks @larebsyed

**Pull request merged**
