### PR TITLE
Refactoring, add universal icon alists

### PR DESCRIPTION
**Pull request by a13**
As described in #2 

Now we can use all-the-icons simply by 
`(setq company-box-icons-alist company-box-icons-all-the-icons)`

It's still in progress (I couldn't find proper icon substitions for some of the images), but looks usable for me.

### CODE REVIEW

**Comment by jsmestad** [comment]
@sebastiencs would you consider pulling this in?

**Comment by a13** [comment]
@sebastiencs Are you still with us?

**Comment by hidaris** [comment]
@sebastiencs ping

**Comment by seagle0128** [comment]
@sebastiencs gental ping...

**Comment by stardiviner** [comment]
I would like to have this patch merged personally.

**Comment by a13** [comment]
@sebastiencs so, what are your thoughts about merging?

**Comment by sebastiencs** [comment]
Merged, thank you @a13 !

**Comment by seagle0128** [comment]
OMG! It broke my configurations https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-company.el#L80. I have to fix it.

**Comment by seagle0128** [comment]
I changed my configurations and improve the `company-box-icons-all-the-icons` . Please try with https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-company.el#L76 . If you think it's great, I'd love create PR for that.

**Comment by a13** [comment]
@seagle0128 thank you for improving `company-box-icons-all-the-icons`! I think PR would be great!

**Comment by seagle0128** [comment]
OK. Let's improve and try for some time and will create a PR later if possible.

**Comment by lambdacn** [comment]
Maybe [doom-emacs company box config](https://github.com/hlissner/doom-emacs/blob/develop/modules/completion/company/config.el#L55) is a better choice

**Comment by a13** [comment]
@lambdacn icon substitutions look nice, though I personally don't like function definitions outside packages (and, especially, in use-package sections)

**Comment by sebastiencs** [comment]
@seagle0128 That looks good ! I'm ready to accept a PR

**Comment by minikN** [comment]
@seagle0128 Sorry but how am I using this? If I do `(setq company-box-icons-alist company-box-icons-all-the-icons)`  I get `Error (use-package): company-box/:init: Symbol’s value as variable is void: company-box-icons-all-the-icons`.

`all-the-icons` fonts are installed.

**Comment by seagle0128** [comment]
@minikN `(setq company-box-icons-alist 'company-box-icons-all-the-icons)`.

**Pull request merged**
