### PR TITLE
Consider company-box-icon-right-margin when computing frame position

### PR DESCRIPTION
**Pull request by KaratasFurkan**
Before:
Screenshot_20200921_165029

After:
Screenshot_20200921_165149

### CODE REVIEW

**Comment by KaratasFurkan** [comment]
This update breaks when `company-box-right-margin` is float, im working on it.

**Comment by sebastiencs** [comment]
@KaratasFurkan Thanks for working on this. Did you find a way to handle float ?

**Comment by KaratasFurkan** [comment]
I could not have a chance to investigate it, I am planning to do emacs related stuff next two days, I will probably fix this too.

**Comment by KaratasFurkan** [comment]
Ready to review :ok_hand:

**Comment by KaratasFurkan** [comment]
Ready to review, final this time :smile:

It turns out modify-frame-parameters function called in one more place too, I just add round to left parameter to work well with float margins.

Sorry for lateness.

**Comment by sebastiencs** [comment]
Thanks for working on this @KaratasFurkan, can you please rebase your branch ?

**Comment by KaratasFurkan** [comment]
@sebastiencs Done :+1:

**Comment by sebastiencs** [comment]
Thanks @KaratasFurkan

**Pull request merged**
