### PR TITLE
Add an option to always show the candidate even if there is only one

### LINKED ISSUE #35: Frontend that always shows candidates
It would be great if there was another frontend that would always show candidates even if there is only one.

### PR DESCRIPTION
**Pull request by ppwwyyxx**
fix #35

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
@sebastiencs

**Comment by MaskRay** [comment]
@sebastiencs  Gentle ping :)

https://github.com/hlissner/doom-emacs/blob/develop/modules/completion/company/config.el#L97

**Comment by valignatev** [comment]
Wow, thanks for this PR!

**Comment by sebastiencs** [comment]
Thanks @ppwwyyxx, sorry for the delay

**Comment by sebastiencs** [comment]
@hlissner it's merged :)
(about https://github.com/hlissner/doom-emacs/blob/develop/modules/completion/company/config.el#L97)

**Pull request merged**
