### PR TITLE
Use () instead of nil in defun argument

### PR DESCRIPTION
**Pull request by conao3**
Hi!
I found strange Elisp form. So I fix it.
Using () instead of nil in defun argument is very strange hack. so I
fix using () instead of nil

### CODE REVIEW

**Comment by a13** [comment]
try to eval these:

```
(eq nil '())

(listp nil)
```

**Comment by conao3** [comment]
Yes, these are the same after `read`.
But many people use empty list as arglist for `defun` or `lambda` when the function does not need any arguments.
This fix contributes this package consistency.

And you are already using an empty list for `defun` [here](https://github.com/sebastiencs/company-box/blob/8fc6168f2d3a0275156dd3fdf46ba496adbab226/company-box-doc.el#L144-L146)
Or you have any reasons to use `nil` instead of an empty list?

**Comment by a13** [comment]
>But many people use empty list as arglist for defun or lambda when the function does not need any arguments.

they do

>This fix contributes this package consistency.

Yes, I'm just telling it's not a critical issue


> And you are already using an empty list for defun here

not me

**Comment by conao3** [comment]
OK. Sorry for your noise. close.

**Pull request closed without merging**
