### PR TITLE
support icons for CIDER company-backend

### PR DESCRIPTION
**Pull request by stardiviner**

### CODE REVIEW

**Comment by stardiviner** [comment]
Don't know why, can't display some type icons.

For example `Document`

image

But can display some other icons:

image

**Comment by stardiviner** [comment]
I changed Document icon into Template. Now they displays fine.

**Comment by stardiviner** [comment]
Can't display Namespace icon too.

image

**Comment by sebastiencs** [comment]
Thanks @stardiviner , do you know if thoses missing icons are missing too with other backends (other than cider) ?

**Comment by stardiviner** [comment]
I thinked about your explaination and reviewed the code of `company-box-icons.el`. Finally understand your explaination. Thanks for that.

My PR code is fine. still weird that why some icons can't be displayed.

**Comment by sebastiencs** [comment]
For `company-box-icons--cider-alist` you need to use symbols defined here:
image

`Misc`, `Enumerator`, ... are not valid

**Comment by stardiviner** [comment]
Thanks @sebastiencs , finally resolved this issue. I'm glad to see it. :+1: 

P.S. This is the first time I realized there are some candidate type items are using same icons. Is it possible to add more different icon images?

**Comment by sebastiencs** [comment]
The default images (`company-box-icons-images`) were taken from vscode.
Looks like they are now in a new repository https://github.com/microsoft/vscode-icons since I grabbed them.
If you're willing to update them please do.

If you want to make a complete new set of icons, please add a new variable, similar to company-box-icons-netbeans, company-box-icons-idea etc.

**Comment by sebastiencs** [comment]
Thank you @stardiviner

**Pull request merged**
